#=================== Define Variable ===================
variables:
  MAJOR_VER: "1"
  MINOR_VER: "0"
  DOC_VERDACCIO_VER: "4.6"
  SERVER_USER_NAME: "verdaccio-agate"
  SERVER_USER_UID: "1000"

#=================== Build Stage ===================
# Build Template
.build-template:
  stage: build
  variables:
    VERSION_TAG: "${MAJOR_VER}.${MINOR_VER}"
  tags:
    - docker
  before_script:
    - GCR_PATH="agate"
  script:
    - |
      docker build \
      --build-arg DOC_VERDACCIO_VER="${DOC_VERDACCIO_VER}" \
      --build-arg VERDACCIO_USER_NAME="${SERVER_USER_NAME}" \
      --build-arg VERDACCIO_USER_UID="${SERVER_USER_UID}" \
      -f ./Dockerfile \
      -t ${GCR_PATH}/${DOC_PROJ_NAME} .
    #tagging X.X.XXX for 
    - echo "Tagging image ${GCR_PATH}/${DOC_PROJ_NAME}:${VERSION_TAG}.${CI_PIPELINE_IID}"
    - docker tag ${GCR_PATH}/${DOC_PROJ_NAME} ${GCR_PATH}/${DOC_PROJ_NAME}:${VERSION_TAG}.${CI_PIPELINE_IID}
    - docker save --output ${DOC_PROJ_NAME}_v${VERSION_TAG}.${CI_PIPELINE_IID}.tar ${GCR_PATH}/${DOC_PROJ_NAME}:${VERSION_TAG}.${CI_PIPELINE_IID}
    - echo "${DOC_PROJ_NAME} BUILD DONE"
  artifacts:
    paths:
      - "${DOC_PROJ_NAME}_v${VERSION_TAG}.${CI_PIPELINE_IID}.tar"
    when: always
    expire_in: 15 minutes

build-verdaccio:
  extends: .build-template
  variables:
    DOC_PROJ_NAME: "verdaccio"
  only:
    refs: 
      - master
    changes:
      - .gitlab-ci.yml
      - .gitlab-ci-verdaccio.yml
      - Docker*

#=================== Deploy Stage ===================
# Deploy Template
.deploy-template:
  stage: deploy
  variables:
    VERSION_TAG: "${MAJOR_VER}.${MINOR_VER}"
  tags:
    - docker
  before_script:
    - LOGIC_KEY=${SERVER_USER_PASS}
    - LOGIC_USER=${SERVER_USER_NAME}
    - LOGIC_IP=${SERVER_HOST}
    - GCR_PATH="agate"
    - zip -r ${DOC_PROJ_NAME}_v${VERSION_TAG}.${CI_PIPELINE_IID}.zip ./verdaccio
  script:
    - sshpass -p "${LOGIC_KEY}" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./*.tar "${LOGIC_USER}"@"${LOGIC_IP}":/home/"${LOGIC_USER}"/
    - sshpass -p "${LOGIC_KEY}" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./*.zip "${LOGIC_USER}"@"${LOGIC_IP}":/home/"${LOGIC_USER}"/
    - |
      sshpass -p "${LOGIC_KEY}" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
      "${LOGIC_USER}"@"${LOGIC_IP}" < "./deployment/scripts/verdaccio-presetup.sh ${SERVER_USER_NAME} ${DOC_PROJ_NAME}_v${VERSION_TAG}.${CI_PIPELINE_IID};"
    - |
      sshpass -p "${LOGIC_KEY}" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
      "${LOGIC_USER}"@"${LOGIC_IP}" < ./deployment/scripts/verdaccio-docker-run.sh ${DOC_PROJ_NAME} ${GCR_PATH}/${DOC_PROJ_NAME} ${VERSION_TAG}.${CI_PIPELINE_IID} ${SERVER_USER_NAME} ${DOC_PUBISH_PORT} ${DOC_PROJ_NAME}_v${VERSION_TAG}.${CI_PIPELINE_IID} "${DOC_CUST_CMD}"
    - echo "${DOC_PROJ_NAME} DEPLOY DONE"

deploy-verdaccio:
  extends: .deploy-template
  variables:
    DOC_PROJ_NAME: "verdaccio"
    DOC_PUBISH_PORT: "80"
    DOC_CUST_CMD: '" "'
  dependencies:
    - build-verdaccio
  needs: ["build-verdaccio"]
  only:
    refs: 
      - master
    changes:
      - .gitlab-ci.yml
      - .gitlab-ci-verdaccio.yml
      - Docker*